### PR TITLE
Associations:associations, user authentication and tweets

### PR DESCRIPTION
**Pull request by adamclasic**
The database associations and validations have been created and tested to be working. The user is also authenticated using username and fully tested. Posting feature has been added for authenticated users.

### CODE REVIEW

**Comment by adamclasic** [comment]
by now I have fixed the rubocop issues. I'm having trouble to push. it might take some time

**Comment by adamclasic** [comment]
Update: I had problem with internet. I have pushed and fixed errors everything is up and running now.

**Comment by adamclasic** [comment]
https://www.loom.com/share/305e6cc571484a1ca468ce54781dd661
https://intense-temple-98550.herokuapp.com/

2nd review request

**Comment by adamclasic** [comment]
https://www.loom.com/share/305e6cc571484a1ca468ce54781dd661
https://intense-temple-98550.herokuapp.com/

3rd review request

**Review by uche-inyama — COMMENTED** [review]
Screenshot from 2020-07-17 07-17-40

**Comment by adamclasic** [comment]
https://intense-temple-98550.herokuapp.com/

https://www.loom.com/share/bd865dfe58ed4057928ef3b498afbe6e

**Pull request merged**
